version: "3.4"
services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"

  client:
    build: ./client
    container_name: pigeonClient
    ports:
      - 5173:5173
    stdin_open: true
    tty: true
  server:
    build: ./server
    ports:
      - "8000:8000"
    depends_on:
      - postgres
