version: "3.4"
services:
  mysql_server:
    image: mysql
    environment:
      - MYSQL_USER=fazt
      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=fazt_db

  client:
    build: ./client
    container_name: pigeonClient
    ports:
      - 5173:5173
    stdin_open: true
    tty: true
  server:
    build: ./server
    ports:
      - "8000:8000"
    depends_on:
      - mysql_server
    environment:
      - MYSQL_HOST=mysql_server
    links:
      - mysql_server
