 CREATE TABLE user(
    username VARCHAR(255) UNIQUE NOT NULL PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE message(
    id INTEGER UNIQUE NOT NULL PRIMARY KEY AUTO_INCREMENT,
    sender VARCHAR(255) UNIQUE NOT NULL ,
    receiver VARCHAR(255) UNIQUE NOT NULL,
    content TEXT,   
    FOREIGN KEY(sender) REFERENCES user(username) ON DELETE CASCADE ,
    FOREIGN KEY(receiver) REFERENCES user(username) ON DELETE CASCADE 
);

CREATE TABLE session(
    session_id VARCHAR(500) UNIQUE NOT NULL PRIMARY KEY,
    username VARCHAR(255) UNIQUE NOT NULL,
    FOREIGN KEY(username) REFERENCES user(username) ON DELETE CASCADE
);

CREATE TABLE chat(
    id VARCHAR(255) NOT NULL PRIMARY KEY,
    owner VARCHAR(255) UNIQUE NOT NULL,
    participant VARCHAR(255) UNIQUE NOT NULL,
    FOREIGN KEY(owner) REFERENCES user(username) ON DELETE CASCADE ,
    FOREIGN KEY(participant) REFERENCES user(username) ON DELETE CASCADE 
);